apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  endpoints:
    interval: 30s
    port: metrics
    scheme: https
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: node-exporter
